### PR TITLE
Add ci layers

### PR DESCRIPTION
**Pull request by aremazeilles**
The CI process should try generating the docker image, and run the test.
It should fail on the beat test as we do not have file. We will see what it states.

So please wait before merging this to see how the CI process goes.

### CODE REVIEW

**Comment by aremazeilles** [comment]
When I am maintainer of a repo, I see usually here information of advancement of the CI process. But I am not maintainer of your repo. 
Can you check whether you see that process taking place on your side?

You can see an example of such process on this other repository I ahve been workin on: [here](https://github.com/aremazeilles/beat_routine/pull/25)

At the bottom of any PR, I see (can you as well?): 

image

I basically asked in the CI process to generate the docker image and to launch the CI test, everytime a Pull Request is made on master, and every time a commit is done on master.

Regarding the docker testing, instead of copying it within each repo, I downoad it in the [CI process](https://github.com/aremazeilles/madrob_beast_pi/blob/5b0e9c3a703aaf32ae6517d5d21f38f16619c521/.github/workflows/pull_request.yml#L30):

```
run:  wget -O test_docker_call.py https://raw.githubusercontent.com/eurobench/docker_test/master/test_docker_call.py
```
as I have it stored in a separate repository: [docker_test](https://github.com/eurobench/docker_test)

**Comment by aremazeilles** [comment]
I actually made another merge request, but this time towards the master of my forks, and I see the test I mentioned to you:
See https://github.com/aremazeilles/madrob_beast_pi/pull/1:

image

**Comment by aremazeilles** [comment]
The CI process failed effectively because we do not have the data for beast: https://github.com/aremazeilles/madrob_beast_pi/pull/1/checks?check_run_id=1208491185

Commenting the test of beast made the trick, until #15 gets solved.

**Comment by Enri2077** [comment]
I don't see "All checks have passed" nor "Some checks haven't completed yet" in this pull request.
Maybe it will only try to run the CI actions after I merge to master?

**Comment by Enri2077** [comment]
Should I merge now?

**Comment by aremazeilles** [comment]
I think you can , nothing bad can happen :)

**Pull request merged**
